install:
- set JAVA_HOME=C:\Program Files\Java\jdk13
- set JAVA_TOOL_OPTIONS=-Dfile.encoding=UTF8
- ./gradlew -version

build_script:
- ./gradlew assemble --no-daemon --info
- ./gradlew updateSHAs --no-daemon --info

test_script:
- ./gradlew check --no-daemon --info -x integTest

cache:
- C:\ProgramData\chocolatey\bin -> appveyor.yml
- C:\ProgramData\chocolatey\lib -> appveyor.yml
