name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: 13
    - name: Cache Gradle packages
      uses: actions/cache@v2
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle', '**/*.gradle.kts') }}
        restore-keys: ${{ runner.os }}-gradle
    - name: Assemble and run tests
      run: |
        GRADLE_ARGS="--info --stacktrace --no-daemon"
        ./gradlew assemble $GRADLE_ARGS
        # integTest task fails starting with 7.5.0
        # https://discuss.elastic.co/t/elasticsearch-6-3-0-unavailable-in-maven-repository/138782/2
        ./gradlew check $GRADLE_ARGS -x integTest
